version: '3'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: "marcio"
      POSTGRES_PASSWORD: "marcio123"
      POSTGRES_DB: "data_marcio"
    ports:
      - "5432:5432"
    networks:
      - pg-network
 
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "marcio@datamarcio.inc"
      PGADMIN_DEFAULT_PASSWORD: "marcio123"
    ports:
      - "8080:80" # Esquerda Externo:Direita Interno
    depends_on:
      - postgres
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge            