INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Açailândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Afonso Cunha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Água Doce do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alcântara', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aldeias Altas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Altamira do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Alegre do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Alegre do Pindaré', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Parnaíba', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Amapá do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Amarante do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anajatuba', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anapurus', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Apicum-Açu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araguanã', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araioses', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arame', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arari', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Axixá', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bacabal', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bacabeira', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bacuri', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bacurituba', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Balsas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barão de Grajaú', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barra do Corda', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barreirinhas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bela Vista do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Belágua', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Benedito Leite', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bequimão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bernardo do Mearim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boa Vista do Gurupi', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bom Jardim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bom Jesus das Selvas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bom Lugar', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brejo', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brejo de Areia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buriti', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buriti Bravo', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buriticupu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buritirana', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cachoeira Grande', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajapió', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajari', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campestre do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cândido Mendes', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cantanhede', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Capinzal do Norte', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carolina', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carutapera', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caxias', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cedral', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Central do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Centro do Guilherme', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Centro Novo do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Chapadinha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cidelândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Codó', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Coelho Neto', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Colinas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Conceição do Lago-Açu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Coroatá', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cururupu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Davinópolis', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dom Pedro', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Duque Bacelar', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Esperantinópolis', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Estreito', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Feira Nova do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fernando Falcão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Formosa da Serra Negra', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fortaleza dos Nogueiras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fortuna', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Godofredo Viana', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gonçalves Dias', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Archer', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Edison Lobão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Eugênio Barros', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Luiz Rocha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Newton Bello', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Governador Nunes Freire', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Graça Aranha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Grajaú', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guimarães', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Humberto de Campos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Icatu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Igarapé do Meio', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Igarapé Grande', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Imperatriz', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaipava do Grajaú', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapecuru Mirim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itinga do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jatobá', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jenipapo dos Vieiras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'João Lisboa', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Joselândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Junco do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lago da Pedra', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lago do Junco', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lago dos Rodrigues', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lago Verde', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lagoa do Mato', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lagoa Grande do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lajeado Novo', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lima Campos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Loreto', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Luís Domingues', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Magalhães de Almeida', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maracaçumé', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marajá do Sena', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maranhãozinho', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mata Roma', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Matinha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Matões', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Matões do Norte', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Milagres do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirador', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Miranda do Norte', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirinzal', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monção', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Montes Altos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Morros', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nina Rodrigues', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Colinas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Iorque', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Olinda do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Olho d`Água das Cunhãs', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Olinda Nova do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paço do Lumiar', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmeirândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paraibano', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Parnarama', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Passagem Franca', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pastos Bons', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulino Neves', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulo Ramos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedreiras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedro do Rosário', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Penalva', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Peri Mirim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Peritoró', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pindaré-Mirim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pinheiro', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pio XII', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirapemas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Poção de Pedras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porto Franco', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porto Rico do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Dutra', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Juscelino', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Médici', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Sarney', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Vargas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Primeira Cruz', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Raposa', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Riachão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribamar Fiquene', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rosário', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sambaíba', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Filomena do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Helena', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Inês', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Luzia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Luzia do Paruá', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Quitéria do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rita', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santana do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Amaro do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio dos Lopes', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Benedito do Rio Preto', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Bento', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Bernardo', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Domingos do Azeitão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Domingos do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Félix de Balsas', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Francisco do Brejão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Francisco do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João Batista', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João do Carú', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João do Paraíso', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João do Soter', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João dos Patos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José de Ribamar', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José dos Basílios', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Luís', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Luís Gonzaga do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Mateus do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Pedro da Água Branca', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Pedro dos Crentes', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Raimundo das Mangabeiras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Raimundo do Doca Bezerra', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Roberto', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Vicente Ferrer', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Satubinha', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Senador Alexandre Costa', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Senador La Rocque', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Serrano do Maranhão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sítio Novo', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sucupira do Norte', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sucupira do Riachão', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tasso Fragoso', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Timbiras', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Timon', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Trizidela do Vale', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tufilândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tuntum', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turiaçu', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turilândia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tutóia', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urbano Santos', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vargem Grande', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Viana', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vila Nova dos Martírios', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vitória do Mearim', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vitorino Freire', 'MA');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Zé Doca', 'MA');

commit;