INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Abadia de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Abadiânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Acreúna', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Adelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Água Fria de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Água Limpa', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águas Lindas de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alexânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aloândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Horizonte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Paraíso de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alvorada do Norte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Amaralina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Americano do Brasil', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Amorinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Anápolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Anhanguera', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Anicuns', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aparecida de Goiânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aparecida do Rio Doce', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aporé', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Araçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aragarças', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aragoiânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Araguapaz', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Arenópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aruanã', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Aurilândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Avelinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Baliza', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Barro Alto', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Bela Vista de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Bom Jardim de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Bom Jesus de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Bonfinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Bonópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Brazabrantes', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Britânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Buriti Alegre', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Buriti de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Buritinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cabeceiras', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cachoeira Alta', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cachoeira de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cachoeira Dourada', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Caçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Caiapônia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Caldas Novas', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Caldazinha', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campestre de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campinaçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campinorte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campo Alegre de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campo Limpo de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campos Belos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Campos Verdes', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Carmo do Rio Verde', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Castelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Catalão', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Caturaí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cavalcante', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Ceres', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cezarina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Chapadão do Céu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cidade Ocidental', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cocalzinho de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Colinas do Sul', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Córrego do Ouro', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Corumbá de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Corumbaíba', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cristalina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cristianópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Crixás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cromínia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Cumari', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Damianópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Damolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Davinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Diorama', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Divinópolis de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Doverlândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Edealina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Edéia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Estrela do Norte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Faina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Fazenda Nova', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Firminópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Flores de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Formosa', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Formoso', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Gameleira de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goianápolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goiandira', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goianésia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goiânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goianira', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Goiatuba', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Gouvelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Guapó', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Guaraíta', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Guarani de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Guarinos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Heitoraí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Hidrolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Hidrolina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Iaciara', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Inaciolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Indiara', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Inhumas', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Ipameri', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Ipiranga de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Iporá', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Israelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Itaberaí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Itaguari', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),'Itaguaru', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itajá', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapaci', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapirapuã', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapuranga', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itarumã', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itauçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itumbiara', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ivolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jandaia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaraguá', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jataí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaupaci', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jesúpolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Joviânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jussara', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lagoa Santa', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Leopoldo de Bulhões', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Luziânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mairipotaba', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mambaí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mara Rosa', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marzagão', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Matrinchã', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maurilândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mimoso de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Minaçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mineiros', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Moiporá', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Alegre de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Montes Claros de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Montividiu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Montividiu do Norte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Morrinhos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Morro Agudo de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mossâmedes', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mozarlândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mundo Novo', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mutunópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nazário', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nerópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Niquelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova América', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Aurora', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Crixás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Glória', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Iguaçu de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Roma', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Veneza', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Brasil', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Gama', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Planalto', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Orizona', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ouro Verde de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ouvidor', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Padre Bernardo', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palestina de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmeiras de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmelo', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palminópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Panamá', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paranaiguara', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paraúna', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Perolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Petrolina de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pilar de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piracanjuba', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piranhas', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirenópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pires do Rio', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Planaltina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pontalina', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porangatu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porteirão', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Portelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Posse', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Professor Jamil', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Quirinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rialma', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rianápolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio Quente', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio Verde', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rubiataba', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sanclerlândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Bárbara de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Cruz de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Fé de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Helena de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Isabel', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rita do Araguaia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rita do Novo Destino', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rosa de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Tereza de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Terezinha de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio da Barra', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio do Descoberto', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Domingos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Francisco de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João d`Aliança', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João da Paraúna', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Luís de Montes Belos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Luíz do Norte', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Miguel do Araguaia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Miguel do Passa Quatro', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Patrício', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Simão', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Senador Canedo', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Serranópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Silvânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Simolândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sítio d`Abadia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taquaral de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Teresina de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Terezópolis de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Três Ranchos', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Trindade', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Trombas', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turvânia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turvelândia', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uirapuru', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uruaçu', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uruana', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urutaí', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Valparaíso de Goiás', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Varjão', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vianópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vicentinópolis', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vila Boa', 'GO');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vila Propício', 'GO');

commit;