INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Amparo de São Francisco', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aquidabã', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aracaju', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arauá', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Areia Branca', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barra dos Coqueiros', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boquim', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brejo Grande', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campo do Brito', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Canhoba', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Canindé de São Francisco', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Capela', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carira', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carmópolis', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cedro de São João', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cristinápolis', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cumbe', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Divina Pastora', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Estância', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Feira Nova', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Frei Paulo', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gararu', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'General Maynard', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gracho Cardoso', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ilha das Flores', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Indiaroba', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itabaiana', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itabaianinha', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itabi', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaporanga d`Ajuda', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Japaratuba', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Japoatã', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lagarto', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Laranjeiras', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Macambira', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Malhada dos Bois', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Malhador', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maruim', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Moita Bonita', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Alegre de Sergipe', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Muribeca', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Neópolis', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nossa Senhora Aparecida', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nossa Senhora da Glória', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nossa Senhora das Dores', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nossa Senhora de Lourdes', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nossa Senhora do Socorro', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pacatuba', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedra Mole', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedrinhas', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pinhão', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirambu', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Poço Redondo', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Poço Verde', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porto da Folha', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Propriá', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Riachão do Dantas', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Riachuelo', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirópolis', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rosário do Catete', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salgado', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Luzia do Itanhy', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rosa de Lima', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santana do São Francisco', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Amaro das Brotas', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Cristóvão', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Domingos', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Francisco', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Miguel do Aleixo', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Simão Dias', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Siriri', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Telha', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tobias Barreto', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tomar do Geru', 'SE');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Umbaúba', 'SE');

commit;