INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Adamantina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Adolfo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aguaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águas da Prata', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águas de Lindóia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águas de Santa Bárbara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águas de São Pedro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Agudos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alambari', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alfredo Marcondes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Altair', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Altinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Alegre', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alumínio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Álvares Florence', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Álvares Machado', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Álvaro de Carvalho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alvinlândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Americana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Américo Brasiliense', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Américo de Campos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Amparo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Analândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Andradina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Angatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anhembi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anhumas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aparecida', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aparecida d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Apiaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araçariguama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araçatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araçoiaba da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aramina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arandu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arapeí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araraquara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Araras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arco-Íris', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arealva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Areias', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Areiópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ariranha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Artur Nogueira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Arujá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aspásia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Assis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Atibaia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Auriflama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Avaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Avanhandava', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Avaré', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bady Bassitt', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Balbinos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bálsamo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bananal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barão de Antonina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barbosa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bariri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barra Bonita', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barra do Chapéu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barra do Turvo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barretos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barrinha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barueri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bastos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Batatais', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bauru', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bebedouro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bento de Abreu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bernardino de Campos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bertioga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bilac', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Birigui', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Biritiba-Mirim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boa Esperança do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bocaina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bofete', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boituva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bom Jesus dos Perdões', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bom Sucesso de Itararé', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Borá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boracéia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Borborema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Borebi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Botucatu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Bragança Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Braúna', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brejo Alegre', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brodowski', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Brotas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buritama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Buritizal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cabrália Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cabreúva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caçapava', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cachoeira Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caconde', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cafelândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caiabu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caieiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caiuá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajamar', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajati', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajobi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cajuru', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campina do Monte Alegre', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campinas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campo Limpo Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campos do Jordão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Campos Novos Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cananéia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Canas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cândido Mota', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cândido Rodrigues', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Canitar', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Capão Bonito', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Capela do Alto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Capivari', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caraguatatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carapicuíba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cardoso', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Casa Branca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cássia dos Coqueiros', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Castilho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Catanduva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Catiguá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cedral', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cerqueira César', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cerquilho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cesário Lange', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Charqueada', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Chavantes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Clementina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Colina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Colômbia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Conchal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Conchas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cordeirópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Coroados', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Coronel Macedo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Corumbataí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cosmópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cosmorama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cotia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cravinhos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cristais Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cruzália', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cruzeiro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cubatão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Cunha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Descalvado', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Diadema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dirce Reis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Divinolândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dobrada', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dois Córregos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dolcinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dourado', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dracena', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Duartina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Dumont', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Echaporã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Eldorado', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Elias Fausto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Elisiário', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Embaúba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Embu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Embu-Guaçu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Emilianópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Engenheiro Coelho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Espírito Santo do Pinhal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Espírito Santo do Turvo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Estiva Gerbi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Estrela d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Estrela do Norte', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Euclides da Cunha Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fartura', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fernando Prestes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fernandópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fernão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ferraz de Vasconcelos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Flora Rica', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Floreal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Flórida Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Florínia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Franca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Francisco Morato', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Franco da Rocha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gabriel Monteiro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gália', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Garça', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gastão Vidigal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Gavião Peixoto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'General Salgado', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Getulina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Glicério', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaiçara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaimbê', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaíra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guapiaçu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guapiara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guará', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaraçaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaraci', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guarani d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guarantã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guararapes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guararema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guaratinguetá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guareí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guariba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guarujá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guarulhos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guatapará', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guzolândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Herculândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Holambra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Hortolândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iacanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iacri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iaras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ibaté', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ibirá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ibirarema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ibitinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ibiúna', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Icém', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iepê', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Igaraçu do Tietê', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Igarapava', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Igaratá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iguape', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ilha Comprida', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ilha Solteira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ilhabela', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Indaiatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Indiana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Indiaporã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Inúbia Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ipaussu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iperó', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ipeúna', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ipiguá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iporanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ipuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iracemápolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Irapuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Irapuru', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaberá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itajobi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaju', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itanhaém', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaóca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapecerica da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapetininga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapeva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapevi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapirapuã Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itápolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaporanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapuí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapura', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itaquaquecetuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itararé', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itariri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itatiba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itatinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itirapina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itirapuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itobi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itupeva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ituverava', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaborandi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaboticabal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jacareí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaci', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jacupiranga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaguariúna', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jales', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jambeiro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jandira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jardinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jarinu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jaú', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jeriquara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Joanópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'João Ramalho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'José Bonifácio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Júlio Mesquita', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jumirim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jundiaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Junqueirópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Juquiá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Juquitiba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lagoinha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Laranjal Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lavínia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lavrinhas', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Leme', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lençóis Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Limeira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lindóia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lins', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lorena', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lourdes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Louveira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lucélia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lucianópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Luís Antônio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Luiziânia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lupércio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lutécia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Macatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Macaubal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Macedônia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Magda', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mairinque', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mairiporã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Manduri', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marabá Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maracaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marapoama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mariápolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marília', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Marinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Martinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Matão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mauá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mendonça', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Meridiano', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mesópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Miguelópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mineiros do Tietê', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mira Estrela', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Miracatu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirandópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirante do Paranapanema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirassol', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mirassolândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mococa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mogi das Cruzes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mogi Guaçu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Moji Mirim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mombuca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monções', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Mongaguá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Alegre do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Alto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Aprazível', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Azul Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Castelo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monte Mor', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Monteiro Lobato', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Morro Agudo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Morungaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Motuca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Murutinga do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nantes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Narandiba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Natividade da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nazaré Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Neves Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nhandeara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nipoã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Aliança', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Campina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Canaã Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Castilho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Europa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Granada', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Guataporanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Independência', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Luzitânia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Odessa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novais', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Horizonte', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nuporanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ocauçu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Óleo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Olímpia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Onda Verde', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Oriente', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Orindiúva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Orlândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Osasco', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Oscar Bressane', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Osvaldo Cruz', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ourinhos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ouro Verde', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ouroeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pacaembu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palestina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmares Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmeira d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Palmital', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Panorama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paraguaçu Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paraibuna', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paraíso', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paranapanema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paranapuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Parapuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pardinho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pariquera-Açu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Parisi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Patrocínio Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulicéia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulínia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulistânia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Paulo de Faria', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pederneiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedra Bela', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedranópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedregulho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedreira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedrinhas Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pedro de Toledo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Penápolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pereira Barreto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pereiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Peruíbe', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piacatu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piedade', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pilar do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pindamonhangaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pindorama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pinhalzinho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piquerobi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piquete', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piracaia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piracicaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piraju', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirajuí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirangi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirapora do Bom Jesus', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirapozinho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pirassununga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Piratininga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pitangueiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Planalto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Platina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Poá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Poloni', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pompéia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pongaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pontal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pontalinda', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pontes Gestal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Populina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porangaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porto Feliz', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Porto Ferreira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Potim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Potirendaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pracinha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pradópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Praia Grande', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pratânia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Alves', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Bernardes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Epitácio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Prudente', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Venceslau', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Promissão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Quadra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Quatá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Queiroz', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Queluz', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Quintana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rafard', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rancharia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Redenção da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Regente Feijó', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Reginópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Registro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Restinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Bonito', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Branco', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Corrente', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão dos Índios', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Grande', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Pires', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ribeirão Preto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rifaina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rincão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rinópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio Claro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio das Pedras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio Grande da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Riolândia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Riversul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rosana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Roseira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rubiácea', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rubinéia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sabino', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sagres', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sales', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sales Oliveira', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salesópolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salmourão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Saltinho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salto de Pirapora', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Salto Grande', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sandovalina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Adélia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Albertina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Bárbara d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Branca', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Clara d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Cruz da Conceição', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Cruz da Esperança', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Cruz das Palmeiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Cruz do Rio Pardo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Ernestina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Fé do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Gertrudes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Isabel', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Lúcia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Maria da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Mercedes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rita d`Oeste', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rita do Passa Quatro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Rosa de Viterbo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Salete', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santana da Ponte Pensa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santana de Parnaíba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Anastácio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo André', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio da Alegria', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio de Posse', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio do Aracanguá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio do Jardim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio do Pinhal', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Expedito', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santópolis do Aguapeí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Bento do Sapucaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Bernardo do Campo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Caetano do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Carlos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Francisco', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João da Boa Vista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João das Duas Pontes', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João de Iracema', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São João do Pau d`Alho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Joaquim da Barra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José da Bela Vista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José do Barreiro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José do Rio Pardo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José do Rio Preto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São José dos Campos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Lourenço da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Luís do Paraitinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Manuel', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Miguel Arcanjo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Paulo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Pedro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Pedro do Turvo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Roque', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Sebastião', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Sebastião da Grama', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Simão', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Vicente', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sarapuí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sarutaiá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sebastianópolis do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Serra Azul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Serra Negra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Serrana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sertãozinho', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sete Barras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Severínia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Silveiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Socorro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sorocaba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sud Mennucci', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Sumaré', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Suzanápolis', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Suzano', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tabapuã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tabatinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taboão da Serra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taciba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taguaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taiaçu', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taiúva', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tambaú', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tanabi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tapiraí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tapiratiba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taquaral', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taquaritinga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taquarituba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taquarivaí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tarabai', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tarumã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tatuí', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Taubaté', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tejupá', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Teodoro Sampaio', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Terra Roxa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tietê', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Timburi', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Torre de Pedra', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Torrinha', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Trabiju', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tremembé', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Três Fronteiras', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tuiuti', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tupã', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tupi Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turiúba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Turmalina', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ubarana', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ubatuba', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ubirajara', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uchoa', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'União Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urânia', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uru', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urupês', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Valentim Gentil', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Valinhos', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Valparaíso', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vargem', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vargem Grande do Sul', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vargem Grande Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Várzea Paulista', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vera Cruz', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vinhedo', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Viradouro', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vista Alegre do Alto', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Vitória Brasil', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Votorantim', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Votuporanga', 'SP');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Zacarias', 'SP');

commit;