INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Afonso Cláudio', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Água Doce do Norte', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Águia Branca', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alegre', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alfredo Chaves', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alto Rio Novo', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anchieta', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Apiacá', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Aracruz', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Atilio Vivacqua', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Baixo Guandu', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Barra de São Francisco', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Boa Esperança', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Bom Jesus do Norte', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Brejetuba', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Cachoeiro de Itapemirim', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Cariacica', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Castelo', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Colatina', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Conceição da Barra', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Conceição do Castelo', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Divino de São Lourenço', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Domingos Martins', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Dores do Rio Preto', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Ecoporanga', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Fundão', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Governador Lindenberg', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Guaçuí', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Guarapari', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Ibatiba', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Ibiraçu', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Ibitirama', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Iconha', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Irupi', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Itaguaçu', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Itapemirim', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Itarana', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Iúna', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Jaguaré', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Jerônimo Monteiro', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'João Neiva', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Laranja da Terra', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Linhares', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Mantenópolis', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Marataízes', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Marechal Floriano', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Marilândia', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Mimoso do Sul', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Montanha', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Mucurici', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Muniz Freire', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Muqui', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Nova Venécia', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Pancas', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Pedro Canário', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Pinheiros', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Piúma', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Ponto Belo', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Presidente Kennedy', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Rio Bananal', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Rio Novo do Sul', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Santa Leopoldina', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Santa Maria de Jetibá', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Santa Teresa', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'São Domingos do Norte', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'São Gabriel da Palha', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'São José do Calçado', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'São Mateus', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'São Roque do Canaã', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Serra', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Sooretama', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Vargem Alta', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Venda Nova do Imigrante', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Viana', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Vila Pavão', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Vila Valério', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Vila Velha', 'ES');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')),  'Vitória', 'ES');

commit;