INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Alvarães', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Amaturá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anamã', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Anori', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Apuí', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Atalaia do Norte', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Autazes', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barcelos', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Barreirinha', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Benjamin Constant', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Beruri', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boa Vista do Ramos', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Boca do Acre', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Borba', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Caapiranga', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Canutama', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Carauari', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Careiro', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Careiro da Várzea', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Coari', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Codajás', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Eirunepé', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Envira', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Fonte Boa', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Guajará', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Humaitá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Ipixuna', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Iranduba', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itacoatiara', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itamarati', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Itapiranga', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Japurá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Juruá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Jutaí', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Lábrea', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Manacapuru', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Manaquiri', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Manaus', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Manicoré', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maraã', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Maués', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nhamundá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Nova Olinda do Norte', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Airão', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Novo Aripuanã', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Parintins', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Pauini', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Presidente Figueiredo', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Rio Preto da Eva', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santa Isabel do Rio Negro', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Santo Antônio do Içá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Gabriel da Cachoeira', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Paulo de Olivença', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'São Sebastião do Uatumã', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Silves', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tabatinga', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tapauá', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tefé', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Tonantins', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Uarini', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urucará', 'AM');
INSERT INTO cidade (id, nome, uf) VALUES ((select nextval('cidade_id_seq')), 'Urucurituba', 'AM');

commit;