INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Amstel Puro Malte Lata 350ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Coca-Cola Pet 1L');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Creme de Leite Lider 200g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Limão Taiti');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Presunto Perdigão');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Batata Monalisa');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Lava-Roupas Liquido Olá');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Mortadela Bologna');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Água Crystal sem Gás 1,5L');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Patinho Bovino');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Linguiça Toscana Sadia');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Salsicha Seara');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Coxa e Sobrecoxa');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Óleo de Soja Liza 900ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Açucar Refinado 1kg');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Milho para Pipoca Tipo 1 Yoki 500g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Açúcar Refinado Alto Alegre 1kg');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Coca-Cola Original 200ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Refresco em Pó Tang Laranja 25g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Coca-Cola Original 220ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Coca-Cola sem Açúcar 200ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Cerveja Pilsen Skol 269ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Cerveja Heineken Garrafa 330ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Cerveja Original Antarctica Garrafa 600ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Cerveja Itaipava 350ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Steak de Frango Seara Tradicional Pacote 100g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Texas Burguer Misto Embalagem 56g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Empanado Sadia Nuggets Frango Embalagem 300g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Molho de Tomate Tradicional Quero 340g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Molho de Tomate Tradicional Heinz 340g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Tempero para Carnes Sazón 60g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Cenoura');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Beterraba');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Berinjela');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Margarina Cremosa com Sal');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Requeijão Cremoso Vigor');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Leite UHT Integral Lider Caixa 1L');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Leite UHT Integral Tirol Caixa 1L');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Leite UHT Integral Frimesa Caixa 1L');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Leite Fermentado Desnatado');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Detergente Ypê Clear 500ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Detergente Ypê Coco 500ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Detergente Ypê Neutro 500ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Limpador Multiuso Veja 500ml');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Sabonete Dove Original 90g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Creme Dental Menta Suave Oral-B 70g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Creme Dental Sorriso Tripla Ação 90g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Ração para Cães Adultos Dog Chow Carne Ao Molho 100g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Ração Úmida para Gatos Adultos 85g');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Chinelo Cartago de Dedo Infantil 23/24');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Chinelo Havaianas Brasil Cinza 39/40');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Chinelo Havaianas Brasil Cinza 41/42');
INSERT INTO PRODUTO (id, nome) VALUES ((select nextval('produto_id_seq')), 'Chinelo Havaianas Slim Gloss Areia 35/36');
